# INDEX OF THE FOLLOWING TOPICS


# MATRICES 

## 1) Addition
## 2)Subraction
## 3) Multiplication
## 4) Determinant
## 5)Transpose
## 6)Adjoint of Matrix
## 7)Inverse of Matrix
## 8) Some properties of Matrices

## 9)  Row Echloan Form 
## 10)Reduced Row Echloan form
## 11) LU Decomposition
## 12)Gaussian Elimination
## 13)Linear Indepedence/Dependence
## 14)Linear Consistency Inconsistency
## 15) Rank of matrix¶
## 16) AUTOMATED THE CODE FORM ANY NORM  L1 ,L2, L3 ......Ln
## 17) Basis Vectors of the subspace spanned
# VECTORS
## 18)Magnitude of Vector
## 19)Unit Vectors
## 20) Addition
## 21) Subraction
## 22)scalar Product
## 23)Dot Product
## 24)Vector Projection
## 25)Linear Transformation
## 26)Basis Changes
## 27)Orthogonal Vectors
## 28)Eigenvalues
## 29)Eigenvectors
## 30)Sigular Value Decomposition(SVD) / Factorization of matrices 



In [4]:

import numpy as np
import random
from sympy import Matrix

### Addition 

In [2]:
x = np.array([[1,2],[3,4]])
y = np.array([[3,4],[8,10]])
x + y

array([[ 4,  6],
       [11, 14]])

### Subraction

In [3]:
x = np.array([[1,2],[3,4]])
y = np.array([[3,4],[8,10]])
x - y

array([[-2, -2],
       [-5, -6]])

### Multiplication

In [4]:
x = np.array([[1,2],[3,4]])
y = np.array([[3,4],[8,10]])
x @ y

array([[19, 24],
       [41, 52]])

## Determinant 

In [5]:
np.linalg.det(x)

-2.0000000000000004

In [6]:
np.linalg.det(y)

-1.9999999999999998

##  Transpose

In [7]:
print('x(Transpose)=',x.T)
print('\n')
print('y(Transpose)=',y.T)

x(Transpose)= [[1 3]
 [2 4]]


y(Transpose)= [[ 3  8]
 [ 4 10]]


### Adjoint of matrix

In [8]:
x = np.array([[1,2],[3,4]])
y = np.array([[3,4],[8,10]])
print('ADJ(x) = ',Matrix(x).adjugate())
print('ADJ(y) = ',Matrix(y).adjugate()) ## sympy library

ADJ(x) =  Matrix([[4, -2], [-3, 1]])
ADJ(y) =  Matrix([[10, -4], [-8, 3]])


### Inverse of Matrix

##### A-1 = (1/Determinant of A) *  Adjoint of  A

In [9]:
x_inv = (1/np.linalg.det(x))*Matrix(x).adjugate()
x_inv


Matrix([
[-2.0,  1.0],
[ 1.5, -0.5]])

###### Through Inbuild function

In [10]:
print('x.inverse = ' ,np.mat(x).I)
print('\n')
print('y.inverse = ' ,np.mat(y).I)


x.inverse =  [[-2.   1. ]
 [ 1.5 -0.5]]


y.inverse =  [[-5.   2. ]
 [ 4.  -1.5]]


## Some Properties of Matrices

In [81]:
A = np.matrix([[2,-4],[3,7]])
B = np.matrix([[8,10],[1,2]])
C = np.matrix([[3,2],[8,12]])

print('A\n',A)
print('B\n', B)
print('C\n', C)
print('\n')

print('a)(AT)T = A')
print('_____________________________________________________________________')
print('(A.T).T = A \n', A.T.T)
print('A \n' , A)
print('')

print('')
print('A-1)-1 = A')
print(' ')
print('(A.inv).inv \n' , A.I.I )
print('')
print('A\n',A)
print('_____________________________________________________________________')

print(' ')
print('(AB)-1 EQUAL TO B-1 A-1')
print('AB. INV = \n', (A@B).I)
print('')
print('B.INV .A.INV \n ' , B.I@A.I)
print('_____________________________________________________________________')

print(' \n')
print('(AB)T = BTAT')
d = A@B
print('(AB).Transpose = \n',d.T)
print('')
print('B.Trans.A.Trans = \n ',(B.T)@(A.T))
print(' ')
print('_____________________________________________________________________')

w = A + B
print('(A+B).T \n', w.T)
print(' ')
print('A.T + B.T \n', A.T + B.T)
print(' ')
print('_____________________________________________________________________')



print('')
print('(AT) -1 = (A-1)\n', (A.I).T)
print('')
print('(AT) -1 = \n',(A.T).I)
print('')



A
 [[ 2 -4]
 [ 3  7]]
B
 [[ 8 10]
 [ 1  2]]
C
 [[ 3  2]
 [ 8 12]]


a)(AT)T = A
_____________________________________________________________________
(A.T).T = A 
 [[ 2 -4]
 [ 3  7]]
A 
 [[ 2 -4]
 [ 3  7]]


A-1)-1 = A
 
(A.inv).inv 
 [[ 2. -4.]
 [ 3.  7.]]

A
 [[ 2 -4]
 [ 3  7]]
_____________________________________________________________________
 
(AB)-1 EQUAL TO B-1 A-1
AB. INV = 
 [[ 0.2821 -0.0769]
 [-0.1987  0.0769]]

B.INV .A.INV 
  [[ 0.2821 -0.0769]
 [-0.1987  0.0769]]
_____________________________________________________________________
 

(AB)T = BTAT
(AB).Transpose = 
 [[12 31]
 [12 44]]

B.Trans.A.Trans = 
  [[12 31]
 [12 44]]
 
_____________________________________________________________________
(A+B).T 
 [[10  4]
 [ 6  9]]
 
A.T + B.T 
 [[10  4]
 [ 6  9]]
 
_____________________________________________________________________

(AT) -1 = (A-1)
 [[ 0.2692 -0.1154]
 [ 0.1538  0.0769]]

(AT) -1 = 
 [[ 0.2692 -0.1154]
 [ 0.1538  0.0769]]



# Row echloan form

In [12]:

mat = np.matrix([[2,1,1],[3,4,5],[6,7,8]])
print("Matrix:\n", mat)

# Method 1 - Using REF

print("\nRow Echelon Form:")
ref = Matrix(mat).echelon_form()
print("REF :\n",np.matrix(ref))


Matrix:
 [[2 1 1]
 [3 4 5]
 [6 7 8]]

Row Echelon Form:
REF :
 [[2 1 1]
 [0 5 7]
 [0 0 -6]]


# Reduced Row echloan form


In [9]:
mat = np.matrix([[2,1,1,6],[3,4,5,8],[6,7,8,16]])
print("Reduced Row Echelon Form:")
rref, n = Matrix(mat).rref()
print("RREF :\n", np.matrix(rref))
print('\nsolutions [   [X],  [Y], [Z]]')
print("Solutions :",np.matrix(rref[:,-1].T))


Reduced Row Echelon Form:
RREF :
 [[1 0 0 10/3]
 [0 1 0 -4/3]
 [0 0 1 2/3]]

solutions [   [X],  [Y], [Z]]
Solutions : [[10/3 -4/3 2/3]]


In [11]:
rref

Matrix([
[1, 0, 0, 10/3],
[0, 1, 0, -4/3],
[0, 0, 1,  2/3]])

# LU Decomposition

In [14]:
from sympy import Matrix
from sympy import init_printing
init_printing()

In [15]:
A = Matrix([[1,2,3],[4,5,6],[10,11,9]])
A

⎡1   2   3⎤
⎢         ⎥
⎢4   5   6⎥
⎢         ⎥
⎣10  11  9⎦

In [16]:
L , U , _ = A.LUdecomposition()

In [17]:
U ## Upper Triangle


⎡1  2   3 ⎤
⎢         ⎥
⎢0  -3  -6⎥
⎢         ⎥
⎣0  0   -3⎦

In [18]:
L ## Lower Triangle

⎡1   0  0⎤
⎢        ⎥
⎢4   1  0⎥
⎢        ⎥
⎣10  3  1⎦

In [19]:
A == L*U

True

## Gaussian Elimination 

In [21]:
from numpy import *
a = array([[1,1,3,15],[1,2,4,21],[1,1,2,13]] , dtype =float)
## define matrix
## Get Rows and Columns
rows = shape(a)[0]
cols = shape(a)[1]
## solution vector to store solutions
x = zeros(cols-1)
## print matrix here
print(a)
print('rows is ',rows)
print('column is ',cols)
print('\n')
## forwarding algorithm here 
for i in range(cols-1):
    for j in range(i+1 , rows):
        a[j ,:]= -(a[j,i]/a[i,i])*a[i , :] + a[j ,:]
       
 ### prining matrix in row echelon form
print('\n row echelon form \n' , a)

### Backsubstitution of algorithm 
for i in arange(rows-1,-1,-1):
    x[i] = (a[i ,-1]-a[ i ,0:cols-1]@x)/a[i , i]
print('\n final answer')
print(x)
print(' [a, b, c ]')

[[ 1.  1.  3. 15.]
 [ 1.  2.  4. 21.]
 [ 1.  1.  2. 13.]]
rows is  3
column is  4



 row echelon form 
 [[ 1.  1.  3. 15.]
 [ 0.  1.  1.  6.]
 [ 0.  0. -1. -2.]]

 final answer
[5. 4. 2.]
 [a, b, c ]


# Linear Independence 

# Q 1) Neither dependent nor independent

In [24]:
from numpy import *
a = array([[1,3,0,0],[2,2,4,0],[3,1,8,0]] , dtype =float)
## define matrix
## Get Rows and Columns
rows = shape(a)[0]
cols = shape(a)[1]
## solution vector to store solutions
x = zeros(cols-1)
## print matrix here
print(a)
print('rows is ',rows)
print('column is ',cols)
print('\n')
## forwarding algorithm here 
for i in range(cols-1):
    for j in range(i+1 , rows):
        a[j ,:]= -(a[j,i]/a[i,i])*a[i , :] + a[j ,:]
       
 ### prining matrix in row echelon form
print('\n row echelon form \n' , a)

### Backsubstitution of algorithm 
for i in arange(rows-1,-1,-1):
    x[i] = (a[i ,-1]-a[ i ,0:cols-1]@x)/a[i , i]
print('\n final answer')
print(x)
print(' [a, b, c ]')

[[1. 3. 0. 0.]
 [2. 2. 4. 0.]
 [3. 1. 8. 0.]]
rows is  3
column is  4



 row echelon form 
 [[ 1.  3.  0.  0.]
 [ 0. -4.  4.  0.]
 [ 0.  0.  0.  0.]]

 final answer
[nan nan nan]
 [a, b, c ]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in double_scalars


 We do not got a , b , c =0 to be linearly independent but we neither got a ,b, c as some value 
 
 So lets calculate dot product of any two vectors 
 
 if a.b != 0 then vectors are neither dependet or independence
 


In [44]:
a = np.array([1,2,3])
b = np.array([3,2,1])
print('a.b = ',np.dot(a,b))
print('so a.b != 0 then vectors are neither dependent or independence')

a.b =  10
so a.b != 0 then vectors are neither dependent or independence


## Q2) Linear Indepedence 

In [26]:
from numpy import *
a = array([[2,3,0],[1,2,0]] , dtype =float)
## define matrix
## Get Rows and Columns
rows = shape(a)[0]
cols = shape(a)[1]
## solution vector to store solutions
x = zeros(cols-1)
## print matrix here
print(a)
print('rows is ',rows)
print('column is ',cols)
print('\n')
## forwarding algorithm here 
for i in range(cols-1):
    for j in range(i+1 , rows):
        a[j ,:]= -(a[j,i]/a[i,i])*a[i , :] + a[j ,:]
       
 ### prining matrix in row echelon form
print('\n row echelon form \n' , a)

### Backsubstitution of algorithm 
for i in arange(rows-1,-1,-1):
    x[i] = (a[i ,-1]-a[ i ,0:cols-1]@x)/a[i , i]
print('\n final answer')
print(x)
print(' [a, b]')
print('\n since a and b are zero vectors are linearly independent ')

[[2. 3. 0.]
 [1. 2. 0.]]
rows is  2
column is  3



 row echelon form 
 [[2.  3.  0. ]
 [0.  0.5 0. ]]

 final answer
[0. 0.]
 [a, b]

 since a and b are zero vectors are linearly independent 


## Q3) Linear depedence

In [27]:
from numpy import *
a = array([[1,1,3,15],[1,2,5,21],[1,1,2,13]] , dtype =float)
## define matrix
## Get Rows and Columns
rows = shape(a)[0]
cols = shape(a)[1]
## solution vector to store solutions
x = zeros(cols-1)
## print matrix here
print(a)
print('rows is ',rows)
print('column is ',cols)
print('\n')
## forwarding algorithm here 
for i in range(cols-1):
    for j in range(i+1 , rows):
        a[j ,:]= -(a[j,i]/a[i,i])*a[i , :] + a[j ,:]
       
 ### prining matrix in row echelon form
print('\n row echelon form \n' , a)

### Backsubstitution of algorithm 
for i in arange(rows-1,-1,-1):
    x[i] = (a[i ,-1]-a[ i ,0:cols-1]@x)/a[i , i]
print('\n final answer')
print(x)
print('[a, b ,c ]')
print('\n since a ,b and c are non-zero vectors are linearly dependent ')

[[ 1.  1.  3. 15.]
 [ 1.  2.  5. 21.]
 [ 1.  1.  2. 13.]]
rows is  3
column is  4



 row echelon form 
 [[ 1.  1.  3. 15.]
 [ 0.  1.  2.  6.]
 [ 0.  0. -1. -2.]]

 final answer
[7. 2. 2.]
[a, b ,c ]

 since a ,b and c are non-zero vectors are linearly dependent 


## Consistency Inconsistency
2x1 − 6x3 = −8 

x2 + 2x3 = 3 

3x1 + 6x2 − 2x3 = −4

Is this system of equations Consistent or Inconsistent?

If |A| !=0, then consistent and unique solutions

•If |A|=0 and 

•(Adj A) B = 0, then consistent and has infinite solutions

•(Adj A) B != 0, then inconsistent 

In [2]:
A = np.mat([[2,0,-6],[0,1,2],[3,6,-2]])
print(A)
print('\n')
detA = np.linalg.det(A)
print('detA = ' , abs(detA))  
print('|detA| !=0, then consistent and unique solutions')

[[ 2  0 -6]
 [ 0  1  2]
 [ 3  6 -2]]


detA =  9.999999999999998
|detA| !=0, then consistent and unique solutions


## Rank of matrix

In [28]:
A = np.array([[7,3,9],[2,5,-8],[-7,-5,7]])
print('A = \n' ,A)
print('\n Rank of Matrix ')
print(np.linalg.matrix_rank(A))

A = 
 [[ 7  3  9]
 [ 2  5 -8]
 [-7 -5  7]]

 Rank of Matrix 
3


# Lets Automate code for any  Norm 


In [2]:
def norm():
    try:
        x = ''
        basket = []
        span = int(input("enter dimention for eg R= 2 ,R= 3 ... "))
        for i in range(0,span):
                x = int(input("enter here "))
                basket.append(abs(x))
        norms  = basket
        n = int(input("enter the Ln norm you want "))
        for k in range(1,n+1):
            t = 0
            for i in norms:
                t += i**k
                lp = t**(1./k)
            print('LP norm  %d: ' %(k) ,'is = ', lp)
            
    except:
        print('error enter again')
norm()

enter dimention for eg R= 2 ,R= 3 ... 2
enter here 3
enter here 4
enter the Ln norm you want 4
LP norm  1:  is =  7.0
LP norm  2:  is =  5.0
LP norm  3:  is =  4.497941445275415
LP norm  4:  is =  4.284572294953817


# Basis Vectors of the subspace spanned 

In [6]:
mat = np.matrix([[2,3,2,-1],[1,4,1,-2],[2,5,-1,4],[2,2,8,-2],[3,1,0,2]])
print('\n',mat.T)
print("Reduced Row Echelon Form:")
rref, n = Matrix(mat.T).rref()
print("RREF :\n", np.matrix(rref))



 [[ 2  1  2  2  3]
 [ 3  4  5  2  1]
 [ 2  1 -1  8  0]
 [-1 -2  4 -2  2]]
Reduced Row Echelon Form:
RREF :
 [[1 0 0 0 8/3]
 [0 1 0 0 -5/3]
 [0 0 1 0 1/9]
 [0 0 0 1 -4/9]]


#### We Can clearly see that in  RREF Column 1 , 2 ,3 ,4 has pivots so these are our  basis For the Subspace Spanned by the Given Vectors
#### So columns or vectors [2,3,2,-1],[1,4,1,-2],[2,5,-1,4],[2,2,8,-2]
#### are our  Basis For the Subspace Spanned by the Given Vectors

# VECTORS

A directed line segment is called as vector 

vector has magnituted and direction

### Magnitude of Vector

a = i + j + k ;

b = 2i -7j - 3k

Calculate magnitude of two vectors

In [38]:
Ua = np.sqrt(1*1 + 1*1 + 1*1)
Ub = np.sqrt(2*2 + -7*-7 + -3*-3)
print('|a| = ', np.sqrt(1*1 + 1*1 + 1*1))
print('|b| = ',np.sqrt(2*2 + -7*-7 + -3*-3))

|a| =  1.7320508075688772
|b| =  7.874007874011811


## Unit Vector
U = a/|a|

a = i + j + k ;

b = 2i -7j - 3k

Calculate unit vectors  of two vectors

we calculated magnitude above 

so 

Unit Vector a = 0.578i + 0.578j + 0.578k

unit vector b = 0.254i - 0.89j -0.381k 


## Addition of two Vectors

In [39]:
Va = np.array([[7],[6],[5]])
Vb = np.array([[9],[4],[2]])
print(Va)
print('\n')
print(Vb)
Va + Vb

[[7]
 [6]
 [5]]


[[9]
 [4]
 [2]]


array([[16],
       [10],
       [ 7]])

## Subraction of Two vectors

In [40]:
Va = np.array([[7],[6],[5]])
Vb = np.array([[9],[4],[2]])
print(Va)
print('\n')
print(Vb)
Va - Vb

[[7]
 [6]
 [5]]


[[9]
 [4]
 [2]]


array([[-2],
       [ 2],
       [ 3]])

# scalar Product

In [41]:
print('5*Va = \n', 5*Va)

5*Va = 
 [[35]
 [30]
 [25]]


# Dot Product

In [42]:
a = np.array([1,3,4,5])
b = np.array([5,7,8,9])
print('a =',a)
print('\nb =',b)
print('\ndot product a.b =',np.dot(a,b))

a = [1 3 4 5]

b = [5 7 8 9]

dot product a.b = 103


# Vector Projection
a on b = (a.b/|b|^2)b

In [43]:
print('projection of vector a on b ')
a2 = np.array([7,6,5])
b2 = np.array([9,4,2])
dot = np.dot(a2 , b2)
deno = abs(Ub)*abs(Ub)
print('a =\n' , Va)
print('\nb =\n' , Vb)
print('\n a on b = (a.b/|b|^2)b')
print('\n a on b = ', dot/deno)

projection of vector a on b 
a =
 [[7]
 [6]
 [5]]

b =
 [[9]
 [4]
 [2]]

 a on b = (a.b/|b|^2)b

 a on b =  1.564516129032258


# Linear Transformation 
Lines are parallel

Origin does not move

In [36]:
x = np.array([[1],[2]])
y = np.array([[2],[3]])
print('let Equation be 5x + 7y')
print('new vector is\n' , 5*x + 7*y)

let Equation be 5x + 7y
new vector is
 [[19]
 [31]]


# Basis change

NewVector  = Inv(New Basis).Old Basis.Oldvector

What will [8,4] from [2,0], [0,2] basis to a new basis of [4,0] and [0,4]

In [54]:
U = np.matrix([[2,0],[0,2]])
v = np.array([[8],[4]])
print(' old Basis\n', U ,'\n')
print('\n old Vector\n ', v,'\n')
New_Basis = np.matrix([[4,0],[0,4]])
print('new basis\n' , New_Basis)
inv_NB = New_Basis.I
print('\n NewVector = Inv(New Basis).Old Basis.Oldvector')
NewVector = inv_NB*U*v
print('\n new Vector \n' ,NewVector)

 old Basis
 [[2 0]
 [0 2]] 


 old Vector
  [[8]
 [4]] 

new basis
 [[4 0]
 [0 4]]

 NewVector = Inv(New Basis).Old Basis.Oldvector

 new Vector 
 [[4.]
 [2.]]


# Orthogonal Vectors

Two vectors are orthogonal if cosx = u.v/|u|.|V| = 90 

or

u.v = 90 (dot Product)

In [19]:
import numpy as np
u = np.array([-3,4])
v = np.array([4,3])
print('u = ',u)
print('\nv =',v)

print('\nu.v = ',np.dot(u,v))
print('\nso u and v are orthogonal vectors ')

u =  [-3  4]

v = [4 3]

u.v =  0

so u and v are orthogonal vectors 


# Eigenvalues and Eigenvectors

In [69]:
A = np.array([[7,3,9],[2,5,-8],[-7,-5,7]])
print('A = \n', A)
print('\nEigenvalues :' ,np.linalg.eigvals(A))
Evalue , Evectors = np.linalg.eig(A)
print('\n Eigenvectors \n:' ,Evectors )

A = 
 [[ 7  3  9]
 [ 2  5 -8]
 [-7 -5  7]]

Eigenvalues : [7.29522829+4.29446066j 7.29522829-4.29446066j 4.40954343+0.j        ]

 Eigenvectors 
: [[-0.64492839+0.j         -0.64492839-0.j         -0.60102927+0.j        ]
 [ 0.59141497+0.20979052j  0.59141497-0.20979052j  0.79395381+0.j        ]
 [-0.218294  -0.37766568j -0.218294  +0.37766568j -0.09165791+0.j        ]]


# Singular Value Decomposition Or Factorization of matrices

In [71]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magics\pylab.py:160: UserWarning: pylab import has clobbered these variables: ['mat', 'random', 'dot', 'norm']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [74]:
from __future__ import division

set_printoptions( precision = 4 , suppress = True)

In [89]:
A = np.array([[7,3,9],[2,5,-8],[-7,-5,7]])
LeftOrtho , diagonal , RightOrtho  = svd(A)

In [97]:
print("Left Orthogonal Matrix  ")
LeftOrtho

Left Orthogonal Matrix  


array([[ 0.3603,  0.9001,  0.2449],
       [-0.6498,  0.0538,  0.7582],
       [ 0.6693, -0.4323,  0.6043]])

In [99]:
print('diagonal Metrix \n\n', diagonal)

diagonal Metrix 

 [14.6524 11.7008  1.8432]


In [96]:
print('Right Orthogonal Matrix \n\n', RightOrtho)

Right Orthogonal Matrix 

 [[-0.2363 -0.3764  0.8958]
 [ 0.8063  0.4385  0.3969]
 [-0.5422  0.8161  0.1998]]
