In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

In [3]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [12]:
X_train

array([[-0.57113639,  1.93793482, -1.44025702, -1.10600179],
       [-0.44940217, -1.33744797,  0.10338597,  0.06735964],
       [-0.20593373, -0.40162432,  0.21772989,  0.06735964],
       [ 0.15926894, -0.16766841,  0.56076167,  0.7192271 ],
       [-1.6667444 , -1.8053598 , -1.44025702, -1.23637528],
       [-1.54501017,  0.06628751, -1.3259131 , -1.36674877],
       [ 1.25487694,  0.06628751,  0.90379344,  1.11034757],
       [-0.44940217,  2.63980256, -1.38308506, -1.36674877],
       [ 0.76794005, -0.16766841,  0.78944952,  0.97997408],
       [-1.17980751, -1.57140389, -0.29681777, -0.32376084],
       [-1.05807328,  0.76815525, -1.3259131 , -1.36674877],
       [ 0.52447161, -0.63558023,  0.73227755,  0.32810662],
       [ 1.0114085 , -0.16766841,  0.67510559,  0.58885361],
       [ 1.62007961,  0.30024342,  1.24682522,  0.7192271 ],
       [-1.42327595,  0.30024342, -1.44025702, -1.36674877],
       [ 1.62007961, -0.16766841,  1.13248129,  0.45848011],
       [ 0.15926894, -0.

In [13]:
X_test

array([[ 0.15926894, -2.03931572,  0.10338597, -0.32376084],
       [ 1.86354806, -0.63558023,  1.30399718,  0.84960059],
       [-0.20593373, -0.63558023,  0.16055793,  0.06735964],
       [-1.17980751, -0.16766841, -1.38308506, -1.36674877],
       [-1.78847862, -0.40162432, -1.38308506, -1.36674877],
       [-0.44940217, -1.57140389, -0.06812992, -0.32376084],
       [ 0.40273739, -0.40162432,  0.27490185,  0.06735964],
       [ 0.40273739, -0.63558023,  0.56076167,  0.7192271 ],
       [-0.20593373, -0.16766841,  0.21772989, -0.06301385],
       [-0.44940217, -1.10349206,  0.33207382, -0.06301385],
       [-1.17980751,  0.06628751, -1.3259131 , -1.49712227],
       [ 0.28100316, -0.63558023,  0.5035897 , -0.06301385],
       [-0.93633906,  1.70397891, -1.26874114, -1.36674877],
       [ 0.52447161,  0.53419934,  1.24682522,  1.63184154],
       [ 2.47221917,  1.70397891,  1.47551307,  0.97997408],
       [-1.17980751,  0.06628751, -1.3259131 , -1.49712227],
       [-1.05807328,  0.

In [26]:
y_train

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=2, p=2,
                     weights='uniform')

In [24]:
y_pred = classifier.predict(X_test)

In [25]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 0  9  2]
 [ 0  1  6]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.90      0.82      0.86        11
 Iris-virginica       0.75      0.86      0.80         7

       accuracy                           0.90        30
      macro avg       0.88      0.89      0.89        30
   weighted avg       0.90      0.90      0.90        30

